### PR TITLE
This resolves #44 , resolves #51

### LINKED ISSUE #44: There should not be a hardcoded table for the mail
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/plugins/system/userlogs/userlogs.php#L676-L692
### Expected result

using a table e.g. via language string or JLayout maybe
### Actual result

hardcoded table

### LINKED ISSUE #51: Profiles? in the Plugin Code
### Steps to reproduce the issue

https://github.com/joomla-projects/gsoc16_recording-action-logs/blob/staging/plugins/system/userlogs/userlogs.php#L628-L629

https://github.com/joomla-projects/gsoc16_recording-action-logs/tree/staging/plugins/system/userlogs/profiles
### Expected result

using a better name
### Actual result

profiles which not fit here.

### PR DESCRIPTION
**Pull request by muhakh**
Pull Request for Issue #44 #51 .
### Summary of Changes
- Made a new layout for the table in the e-mail
- Changed the name of folder/file profiles/profile.xml to forms/userlogs.xml

### CODE REVIEW

File: plugins/system/userlogs/layouts/logstable.php [hunk 1]
```diff
@@ -0,0 +1,40 @@
+<?php
+/**
+ * @package	 Joomla.Administrator
+ * @subpackage  com_userlogs
+ *
+ * @copyright   Copyright (C) 2005 - 2016 Open Source Matters, Inc. All rights reserved.
+ * @license	 GNU General Public License version 2 or later; see LICENSE.txt
+ */
+
+defined('_JEXEC') or die;
```
Comment (zero-24) [inline plugins/system/userlogs/layouts/logstable.php:10]: please add a clean line after this :smile:

File: plugins/system/userlogs/layouts/logstable.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+$lang = JFactory::getLanguage();
+$source = JPATH_ADMINISTRATOR . '/components/' . 'com_userlogs';
+
+$lang->load("com_userlogs", JPATH_ADMINISTRATOR, null, false, true)
```
Comment (zero-24) [inline plugins/system/userlogs/layouts/logstable.php:14]: please use `'com_userlogs'` here and in the next line

**Comment by zero-24** [comment]
looks much better now. Thanks :+1:
